//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int FundId { get; set; }
        public string FundName { get; set; }
        public string FundCode { get; set; }
        public string Portfolio { get; set; }
    }
}
